config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     coins GET    /coins(.:format)                                                                         coins#index
#                           POST   /coins(.:format)                                                                         coins#create
#                  new_coin GET    /coins/new(.:format)                                                                     coins#new
#                 edit_coin GET    /coins/:id/edit(.:format)                                                                coins#edit
#                      coin GET    /coins/:id(.:format)                                                                     coins#show
#                           PATCH  /coins/:id(.:format)                                                                     coins#update
#                           PUT    /coins/:id(.:format)                                                                     coins#update
#                           DELETE /coins/:id(.:format)                                                                     coins#destroy
#                      root GET    /                                                                                        coins#index
#               coins_index GET    /coins/index(.:format)                                                                   coins#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :mining_types
  resources :coins do
    member do
      get 'mostrar'
    end
  end

  get 'profile', to: 'mining_types#index'
  root 'welcome#index'

  # get 'mostrar' to: 'coins#mostrar'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control", placeholder: "Proof of Work" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class: "form-control", placeholder: "PoW" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:'btn btn-primary' %>
  </div>
<% end %>

<br>

app/views/mining_types/edit.html.erb
<h1><%= t('editing.mining_type') %></h1>

<%= render 'form', mining_type: @mining_type%>

<%= link_to t('links.show'), @mining_type, class:'btn btn-primary' %> |
<%= link_to t('links.back'), mining_types_path, class:'btn btn-primary' %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('mining_type') %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('coin.description') %></th>
      <th><%= t('coin.acronym') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.mining_type'), new_mining_type_path, class:"btn btn-primary" %>
<%= link_to t('link.back'), root_path, class:"btn btn-secondary" %>

app/views/mining_types/new.html.erb
<h1><%= t('new.mining_type') %></h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to t('links.back'), mining_types_path, class:'btn btn-primary' %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">
    <strong><%= label_tag nil, @mining_type.class.human_attribute_name(:description) %></strong>
    <%= text_field_tag nil, @mining_type.description, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <strong><%= label_tag nil, @mining_type.class.human_attribute_name(:acronym) %></strong>
    <%= text_field_tag nil, @mining_type.acronym, class:"form-control", disabled: true %>
  </div>
  <div class="form-group">
    <strong><%= label_tag nil, @mining_type.class.human_attribute_name(:coins) %></strong>
    <% if @mining_type.coins.any? %>
      <table class="table table-hover table-sm">
        <thead class="thead-dark">
          <tr>
            <th><%= t('activerecord.attributes.coin.description') %> </th>
            <th><%= t('activerecord.attributes.coin.acronym') %></th>
            <th><%= t('activerecord.attributes.coin.image') %></th>
          </tr>
        </thead>

        <tbody>
          <% @mining_type.coins.each do |coin|%>
            <tr>
              <td><%= coin.description %></td>
              <td><%= coin.acronym %></td>
              <td><img src="<%= coin.url_image %> "width=35 height=35 /></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p> <%= t('mining_type.no_coins') %> </p>
    <% end %>

  </div>
</form>

<%= link_to t('links.edit'), edit_mining_type_path(@mining_type), class:'btn btn-primary' %> |
<%= link_to t('links.back'), mining_types_path, class:'btn btn-primary' %>