config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     coins GET    /coins(.:format)                                                                         coins#index
#                           POST   /coins(.:format)                                                                         coins#create
#                  new_coin GET    /coins/new(.:format)                                                                     coins#new
#                 edit_coin GET    /coins/:id/edit(.:format)                                                                coins#edit
#                      coin GET    /coins/:id(.:format)                                                                     coins#show
#                           PATCH  /coins/:id(.:format)                                                                     coins#update
#                           PUT    /coins/:id(.:format)                                                                     coins#update
#                           DELETE /coins/:id(.:format)                                                                     coins#destroy
#                      root GET    /                                                                                        coins#index
#               coins_index GET    /coins/index(.:format)                                                                   coins#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :mining_types
  resources :coins do
    member do
      get 'mostrar'
    end
  end

  get 'profile', to: 'mining_types#index'
  root 'welcome#index'

  # get 'mostrar' to: 'coins#mostrar'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coin.rb
# == Schema Information
#
# Table name: coins
#
#  id             :bigint           not null, primary key
#  acronym        :string
#  description    :string
#  url_image      :string
#  value          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  mining_type_id :bigint
#
# Indexes
#
#  index_coins_on_mining_type_id  (mining_type_id)
#
# Foreign Keys
#
#  fk_rails_...  (mining_type_id => mining_types.id)
#
class Coin < ApplicationRecord
  belongs_to :mining_type
end

app/controllers/coins_controller.rb
require './lib/base'
require './lib/api'

class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy mostrar]
  before_action :set_mining_types_option, only: %i[ new edit update create]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all

    # coin_value

    respond_to do |format|
      format.html
      format.js
    end

    if params[:acronym]
      acronym = params[:acronym]
      coin = Coin.find_by(acronym: acronym)
      api = Api::Base.new
      value = api.request(:get, "https://api.coinbase.com/v2/prices/#{acronym.downcase}-usd/spot")
      coin.value = value
      coin.save
    end

    api = Api::Base.new
    @a = api.request(:get, "https://api.coinbase.com/v2/prices/btc-usd/spot")
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  def mostrar
  end



  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    def set_mining_types_option
      @mining_types_option = MiningType.all.pluck(:description, :id)
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end

    def coin_value

    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_coin_value.html.erb
<%= coin.value %> - USD

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control", placeholder: "Bitcoin"%>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class: "form-control", placeholder: "BTC" %>
  </div>

  <div class="form-group">
    <%= form.label :url_image %>
    <%= form.text_field :url_image, class: "form-control", placeholder: "http://img.ur/bitcoin.png" %>
    <%= coin.url_image.present? ? (image_tag coin.url_image, width: 30, height: 30) : ""%>
  </div>

  <div class="form-group">
    <%= form.label :mining_type %>
    <%= form.select("mining_type_id", @mining_types_option, {include_blank: t('select')}, class: "form-control" ) %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

<br>

app/views/coins/edit.html.erb
<h1><%= t('editing.coin') %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.show'), @coin, class: 'btn btn-primary' %> |
<%= link_to t('links.back'), coins_path, class: 'btn btn-primary' %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('coin') %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th class="coin-image"><%= t('activerecord.attributes.coin.image') %></th>
      <th><%= t('activerecord.attributes.coin.description') %> </th>
      <th><%= t('activerecord.attributes.coin.acronym') %></th>
      <th><%= t('activerecord.attributes.coin.value') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><img src="<%= coin.url_image %> "width=35 height=35 /></td>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td id="coin-<%= coin.id %>"><%= render "coin_value", coin: coin %>
          <%= form_tag(coins_path, method: :get , id: "value-form", remote: true) do %>
            <%= hidden_field_tag "acronym", "#{coin.acronym}"%>
          <% end %></td>
        <td><%= link_to t('links.show'), coin %></td>
        <td><%= link_to t('links.edit'), edit_coin_path(coin) %></td>
        <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: 'You sure bout dat?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.coin'), new_coin_path, class:"btn btn-primary" %>
<%= link_to t('links.back'), root_path, class:"btn btn-secondary" %>

<script>
  value_form = document.querySelectorAll("#value-form");
  const interval = setInterval(function() {
    for (var i = 0; i < value_form.length; i++){
      // console.log(value_form[i].innerHTML);
      console.log(i)
      // Rails.fire(value_form[i], 'submit')
      Rails.handleRemote.call(value_form[i])
    }
  }, 15000);
</script>

app/views/coins/index.js.erb
$('#coin-<%= Coin.find_by(acronym: params[:acronym]).id %>').html(" <%= j render '/coins/coin_value', coin: Coin.find_by(acronym: params[:acronym]) %> ");

app/views/coins/mostrar.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Url image:</strong>
  <%= image_tag @coin.url_image, width: 30, height: 30 %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/coins/new.html.erb
<h1><%= t('new.coin') %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.back'), coins_path, class: 'btn btn-primary'%>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:description) %>
    <%= text_field_tag nil, @coin.description, class:"form-control", disabled: true  %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:acronym) %>
    <%= text_field_tag nil, @coin.acronym, class:"form-control", disabled: true  %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:url_image) %>
    <%= image_tag @coin.url_image, width: 30, height: 30 %>
    <%= text_field_tag nil, @coin.url_image, class:"form-control", disabled: true  %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:mining_type) %>
    <%= text_field_tag nil, @coin.mining_type.description, class:"form-control", disabled: true  %>
  </div>

  <div class="form-group">
    <%= label_tag nil, "Valor" %>
    <%=  %>

  </div>
</form>

<%= link_to t('links.edit'), edit_coin_path(@coin), class: 'btn btn-primary'%> |
<%= link_to t('links.back'), coins_path, class: 'btn btn-primary'%>